### ISSUE TITLE
unicode encoding issue

### ISSUE THREAD

**Issue by 7underlines** [prantlf/v-json#1]
I have this PHP script:
```PHP
<?php
$url = 'https://example.com/Bjökovit.jpg';
$e = json_encode($url);
echo $e; // output: https:\/\/example.com\/Bj\u00f6kovit.jpg
```
And this V code:
```V
import prantlf.json as prantlfjson

fn main() {
	url := 'https://example.com/Bjökovit.jpg'
	e := prantlfjson.stringify(url, prantlfjson.StringifyOpts{escape_unicode: true, escape_slashes: true})
	println(e) // outputs: https:\/\/example.com\/Bj\uf6kovit.jpg
}
```
How can I get the V version to output the same as the PHP version?
VSCode gives `Invalid unicode sequence in json` for the above output. And JSON parsing it in PHP also doesn't work.

**Comment by prantlf** [comment]
Congratulations, you found a bug! :-) 

According to the [spec](https://www.json.org/), the hexadecimal numbers after `\u` have to be always padded to 4 digits. The valid output has to be `Bj\u00f6kovit`.

I published [v0.1.1](https://github.com/prantlf/v-json/releases/tag/v0.1.1) with the fix. Thanks for reporting this! I'm sorry for the trouble.

**Comment by 7underlines** [comment]
Thanks for the quick fix! It works now.

**Comment by prantlf** [comment]
Thanks for letting me know! Let's close this issue then.
